//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.05 at 02:37:38 PM CEST 
//


package app.jaxb_model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{www.assembly.gov.rs/acts}part"/>
 *           &lt;element ref="{www.assembly.gov.rs/acts}chapter"/>
 *           &lt;element ref="{www.assembly.gov.rs/acts}section"/>
 *           &lt;element ref="{www.assembly.gov.rs/acts}subsection"/>
 *           &lt;element ref="{www.assembly.gov.rs/acts}article"/>
 *           &lt;element ref="{www.assembly.gov.rs/acts}paragraph"/>
 *           &lt;element ref="{www.assembly.gov.rs/acts}clause"/>
 *           &lt;element ref="{www.assembly.gov.rs/acts}subclause"/>
 *           &lt;element ref="{www.assembly.gov.rs/acts}indent"/>
 *           &lt;element ref="{www.assembly.gov.rs/acts}content"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="targetId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="operation" use="required" type="{www.assembly.gov.rs/amendments}operation" />
 *       &lt;attribute name="position" type="{www.assembly.gov.rs/amendments}position" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "part",
    "chapter",
    "section",
    "subsection",
    "article",
    "paragraph",
    "clause",
    "subclause",
    "indent",
    "content"
})
@XmlRootElement(name = "target", namespace = "www.assembly.gov.rs/amendments")
public class Target {

    protected Part part;
    protected Chapter chapter;
    protected Section section;
    protected Subsection subsection;
    protected Article article;
    protected Paragraph paragraph;
    protected Clause clause;
    protected Subclause subclause;
    protected Indent indent;
    protected Data content;
    @XmlAttribute(name = "targetId", required = true)
    protected String targetId;
    @XmlAttribute(name = "operation", required = true)
    protected Operation operation;
    @XmlAttribute(name = "position")
    protected Position position;
    @XmlAttribute(name = "type")
    @XmlSchemaType(name = "anySimpleType")
    protected String type;

    /**
     * Gets the value of the part property.
     * 
     * @return
     *     possible object is
     *     {@link Part }
     *     
     */
    public Part getPart() {
        return part;
    }

    /**
     * Sets the value of the part property.
     * 
     * @param value
     *     allowed object is
     *     {@link Part }
     *     
     */
    public void setPart(Part value) {
        this.part = value;
    }

    /**
     * Gets the value of the chapter property.
     * 
     * @return
     *     possible object is
     *     {@link Chapter }
     *     
     */
    public Chapter getChapter() {
        return chapter;
    }

    /**
     * Sets the value of the chapter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Chapter }
     *     
     */
    public void setChapter(Chapter value) {
        this.chapter = value;
    }

    /**
     * Gets the value of the section property.
     * 
     * @return
     *     possible object is
     *     {@link Section }
     *     
     */
    public Section getSection() {
        return section;
    }

    /**
     * Sets the value of the section property.
     * 
     * @param value
     *     allowed object is
     *     {@link Section }
     *     
     */
    public void setSection(Section value) {
        this.section = value;
    }

    /**
     * Gets the value of the subsection property.
     * 
     * @return
     *     possible object is
     *     {@link Subsection }
     *     
     */
    public Subsection getSubsection() {
        return subsection;
    }

    /**
     * Sets the value of the subsection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subsection }
     *     
     */
    public void setSubsection(Subsection value) {
        this.subsection = value;
    }

    /**
     * Gets the value of the article property.
     * 
     * @return
     *     possible object is
     *     {@link Article }
     *     
     */
    public Article getArticle() {
        return article;
    }

    /**
     * Sets the value of the article property.
     * 
     * @param value
     *     allowed object is
     *     {@link Article }
     *     
     */
    public void setArticle(Article value) {
        this.article = value;
    }

    /**
     * Gets the value of the paragraph property.
     * 
     * @return
     *     possible object is
     *     {@link Paragraph }
     *     
     */
    public Paragraph getParagraph() {
        return paragraph;
    }

    /**
     * Sets the value of the paragraph property.
     * 
     * @param value
     *     allowed object is
     *     {@link Paragraph }
     *     
     */
    public void setParagraph(Paragraph value) {
        this.paragraph = value;
    }

    /**
     * Gets the value of the clause property.
     * 
     * @return
     *     possible object is
     *     {@link Clause }
     *     
     */
    public Clause getClause() {
        return clause;
    }

    /**
     * Sets the value of the clause property.
     * 
     * @param value
     *     allowed object is
     *     {@link Clause }
     *     
     */
    public void setClause(Clause value) {
        this.clause = value;
    }

    /**
     * Gets the value of the subclause property.
     * 
     * @return
     *     possible object is
     *     {@link Subclause }
     *     
     */
    public Subclause getSubclause() {
        return subclause;
    }

    /**
     * Sets the value of the subclause property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subclause }
     *     
     */
    public void setSubclause(Subclause value) {
        this.subclause = value;
    }

    /**
     * Gets the value of the indent property.
     * 
     * @return
     *     possible object is
     *     {@link Indent }
     *     
     */
    public Indent getIndent() {
        return indent;
    }

    /**
     * Sets the value of the indent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Indent }
     *     
     */
    public void setIndent(Indent value) {
        this.indent = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link Data }
     *     
     */
    public Data getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link Data }
     *     
     */
    public void setContent(Data value) {
        this.content = value;
    }

    /**
     * Gets the value of the targetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * Sets the value of the targetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetId(String value) {
        this.targetId = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link Operation }
     *     
     */
    public Operation getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operation }
     *     
     */
    public void setOperation(Operation value) {
        this.operation = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setPosition(Position value) {
        this.position = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
