//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:23:29 AM CEST 
//


package app.jaxb_model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{www.assembly.gov.rs/acts}article"/>
 *         &lt;element ref="{www.assembly.gov.rs/acts}paragraph"/>
 *         &lt;element ref="{www.assembly.gov.rs/acts}clause"/>
 *         &lt;element ref="{www.assembly.gov.rs/acts}subclause"/>
 *         &lt;element ref="{www.assembly.gov.rs/acts}indent"/>
 *       &lt;/choice>
 *       &lt;attribute name="targetId" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="position" type="{www.assembly.gov.rs/acts}position" />
 *       &lt;attribute name="operation" type="{www.assembly.gov.rs/acts}operation" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "article",
    "paragraph",
    "clause",
    "subclause",
    "indent"
})
@XmlRootElement(name = "target")
public class Target {

    protected Article article;
    protected Paragraph paragraph;
    protected Clause clause;
    protected Subclause subclause;
    protected Indent indent;
    @XmlAttribute(name = "targetId")
    @XmlSchemaType(name = "anySimpleType")
    protected String targetId;
    @XmlAttribute(name = "position")
    protected Position position;
    @XmlAttribute(name = "operation")
    protected Operation operation;

    /**
     * Gets the value of the article property.
     * 
     * @return
     *     possible object is
     *     {@link Article }
     *     
     */
    public Article getArticle() {
        return article;
    }

    /**
     * Sets the value of the article property.
     * 
     * @param value
     *     allowed object is
     *     {@link Article }
     *     
     */
    public void setArticle(Article value) {
        this.article = value;
    }

    /**
     * Gets the value of the paragraph property.
     * 
     * @return
     *     possible object is
     *     {@link Paragraph }
     *     
     */
    public Paragraph getParagraph() {
        return paragraph;
    }

    /**
     * Sets the value of the paragraph property.
     * 
     * @param value
     *     allowed object is
     *     {@link Paragraph }
     *     
     */
    public void setParagraph(Paragraph value) {
        this.paragraph = value;
    }

    /**
     * Gets the value of the clause property.
     * 
     * @return
     *     possible object is
     *     {@link Clause }
     *     
     */
    public Clause getClause() {
        return clause;
    }

    /**
     * Sets the value of the clause property.
     * 
     * @param value
     *     allowed object is
     *     {@link Clause }
     *     
     */
    public void setClause(Clause value) {
        this.clause = value;
    }

    /**
     * Gets the value of the subclause property.
     * 
     * @return
     *     possible object is
     *     {@link Subclause }
     *     
     */
    public Subclause getSubclause() {
        return subclause;
    }

    /**
     * Sets the value of the subclause property.
     * 
     * @param value
     *     allowed object is
     *     {@link Subclause }
     *     
     */
    public void setSubclause(Subclause value) {
        this.subclause = value;
    }

    /**
     * Gets the value of the indent property.
     * 
     * @return
     *     possible object is
     *     {@link Indent }
     *     
     */
    public Indent getIndent() {
        return indent;
    }

    /**
     * Sets the value of the indent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Indent }
     *     
     */
    public void setIndent(Indent value) {
        this.indent = value;
    }

    /**
     * Gets the value of the targetId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * Sets the value of the targetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetId(String value) {
        this.targetId = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setPosition(Position value) {
        this.position = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link Operation }
     *     
     */
    public Operation getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Operation }
     *     
     */
    public void setOperation(Operation value) {
        this.operation = value;
    }

}
