//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.07 at 02:54:13 AM CEST 
//


package app.jaxb_model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="PART"/>
 *     &lt;enumeration value="CHAPTER"/>
 *     &lt;enumeration value="SECTION"/>
 *     &lt;enumeration value="SUBSECTION"/>
 *     &lt;enumeration value="ARTICLE"/>
 *     &lt;enumeration value="PARAGRAPH"/>
 *     &lt;enumeration value="CLAUSE"/>
 *     &lt;enumeration value="SUBCLAUSE"/>
 *     &lt;enumeration value="INDENT"/>
 *     &lt;enumeration value="CONTENT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "type", namespace = "www.assembly.gov.rs/amendments/")
@XmlEnum
public enum Type {

    PART,
    CHAPTER,
    SECTION,
    SUBSECTION,
    ARTICLE,
    PARAGRAPH,
    CLAUSE,
    SUBCLAUSE,
    INDENT,
    CONTENT;

    public String value() {
        return name();
    }

    public static Type fromValue(String v) {
        return valueOf(v);
    }

}
